title: NadindraDev
markdown: kramdown
url: "https://karimiariqn.my.id/dev/"
baseurl: "/dev"

# for atom feed
author: 
  name: Karimi Ariq
  email: mail@karimiariqn.my.id

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-admin

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
